title: <p align="center"> Avinaash Padmanabhan </p>

logo: "/images/profilepic.png?raw=true"

description:
  <p align="center">
  <a href="Resume 2021 .pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/avinaash-padmanabhan-0748aa173/">LinkedIn</a> |
  <a href="https://github.com/AvinaashP">GitHub</a>
  </p>
  
  <p align="justify">
  I am a graduate of Carnegie Mellon with a Bachelor of Science in Statistics and Machine Learning
  <br><br>
  I have a deep interest in machine learning and data analysis and its applications in business and investing 
  <br><br>
  </p>



theme: jekyll-theme-minimal
